### ISSUE TITLE
Improved fonts cannot display Chinese and Arabic

### ISSUE THREAD

**Issue by MapleEve** [Phobos-developers/PhobosSupplementaries#3]
It's so weird that replaced fnt and the Chinese and Arabic characters is blank.

**Comment by chaserli** [comment]
It's not supported yet. If you want to include Chinese characters you can use this one for a temporary placeholder, which supports most Chinese characters yet include the ⚡⌚⛏symbol.

[https://bbs.ra2diy.com/forum.php?mod=viewthread&tid=17893](https://bbs.ra2diy.com/forum.php?mod=viewthread&tid=17893)

**Comment by Metadorius** [comment]
More character ranges are always welcomed in the font.

**Comment by MapleEve** [comment]
> It's not supported yet. If you want to include Chinese characters you can use this one for a temporary placeholder, which supports most Chinese characters yet include the ⚡⌚⛏symbol.
> 
> https://bbs.ra2diy.com/forum.php?mod=viewthread&tid=17893

That sounds great. But the forum is currently unreachable. Keep in touch.
